# Generated by Django 5.2.10 on 2026-02-06 01:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text="User's phone number", max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890 or 1234567890. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('groomer', 'Groomer'), ('customer', 'Customer')], default='customer', help_text='Type of user account', max_length=20),
        ),
    ]
