# Generated by Django 5.2.10 on 2026-02-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('groomer_manager', 'Groomer Manager'), ('groomer', 'Groomer'), ('customer', 'Customer')], default='customer', help_text='Type of user account', max_length=20),
        ),
    ]
