# Generated by Django 5.2.10 on 2026-01-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_groomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groomer',
            name='image_url',
        ),
        migrations.AddField(
            model_name='groomer',
            name='image',
            field=models.ImageField(blank=True, help_text="Upload groomer's photo", null=True, upload_to='groomer_images/'),
        ),
    ]
