# Generated by Django 5.2.10 on 2026-01-28 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_groomer_image_url_groomer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='groomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mainapp.groomer'),
        ),
    ]
