# Generated by Django 5.2.10 on 2026-01-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_appointment_groomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WeightRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Small (0-15 lbs)', max_length=100, unique=True)),
                ('min_weight', models.DecimalField(decimal_places=2, help_text='Minimum weight in lbs', max_digits=6)),
                ('max_weight', models.DecimalField(decimal_places=2, help_text='Maximum weight in lbs', max_digits=6)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra charge for this weight range', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='dog_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dog's weight in lbs (measured at shop)", max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='exempt_from_surcharge',
            field=models.BooleanField(default=False, help_text="If checked, this service won't apply weight range surcharges"),
        ),
        migrations.AddField(
            model_name='appointment',
            name='weight_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mainapp.weightrange'),
        ),
        migrations.CreateModel(
            name='ServiceBreedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this service + breed combination', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='mainapp.breed')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_prices', to='mainapp.service')),
            ],
            options={
                'ordering': ['service__name', 'breed__name'],
                'unique_together': {('service', 'breed')},
            },
        ),
    ]
