# Generated by Django 5.2.10 on 2026-01-29 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_breed_weightrange_appointment_dog_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedWeightSurcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Breed-specific surcharge for this weight range', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_surcharges', to='mainapp.breed')),
                ('weight_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_surcharges', to='mainapp.weightrange')),
            ],
            options={
                'ordering': ['breed__name', 'weight_range__order', 'weight_range__name'],
                'unique_together': {('breed', 'weight_range')},
            },
        ),
    ]
