# Generated by Django 5.2.10 on 2026-01-29 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_breedweightsurcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Toy Breeds, Double-Coated Breeds', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this breed group')),
                ('default_base_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Default base price for services in this group', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeightRangeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Standard 3-Range System, Small/Large System', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this weight range template')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='breed',
            name='breed_pricing_complex',
            field=models.BooleanField(default=False, help_text='Mark if this breed has complex pricing rules requiring manual review'),
        ),
        migrations.AddField(
            model_name='breed',
            name='clone_note',
            field=models.TextField(blank=True, help_text='Note about why pricing was cloned from another breed'),
        ),
        migrations.AddField(
            model_name='breed',
            name='coat_types',
            field=models.CharField(blank=True, choices=[('smooth', 'Smooth/Short'), ('double_coated', 'Double-Coated'), ('wire', 'Wire/Haired'), ('curly', 'Curly/Wavy'), ('long', 'Long/Silky'), ('hairless', 'Hairless'), ('comb', 'Combination')], help_text='Primary coat type', max_length=30),
        ),
        migrations.AddField(
            model_name='breed',
            name='pricing_cloned_from',
            field=models.ForeignKey(blank=True, help_text='If pricing was cloned from another breed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cloned_to', to='mainapp.breed'),
        ),
        migrations.AddField(
            model_name='breed',
            name='typical_weight_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical maximum weight (lbs) for pricing defaults', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='typical_weight_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical minimum weight (lbs) for pricing defaults', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Breed group for pricing inheritance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breeds', to='mainapp.breedgroup'),
        ),
    ]
