# Generated by Django 5.2.10 on 2026-01-29 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_breedgroup_weightrangetemplate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='coat_types',
        ),
    ]
