# Generated by Django 5.2.10 on 2026-01-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_breed_coat_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dog_breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mainapp.breed'),
        ),
    ]
