# Generated by Django 5.2.10 on 2026-01-29 20:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_appointment_dog_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of booking (for historical accuracy)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890 or 1234567890. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='groomer',
            name='image',
            field=models.ImageField(blank=True, help_text="Upload groomer's photo", null=True, upload_to='groomer_images/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
