# Generated by Django 5.2.10 on 2026-01-29 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_appointment_price_at_booking_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breed',
            name='group',
        ),
        migrations.DeleteModel(
            name='BreedGroup',
        ),
    ]
