# Generated by Django 5.2.10 on 2026-01-29 23:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_breed_group_delete_breedgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='typical_weight_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical maximum weight (lbs) for default pricing reference', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='typical_weight_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Typical minimum weight (lbs) for default pricing reference', max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='BreedServiceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True, help_text='Whether this service is offered for this breed')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this service (empty to use service default)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_mappings', to='mainapp.breed')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed_mappings', to='mainapp.service')),
            ],
            options={
                'ordering': ['breed__name', 'service__name'],
                'unique_together': {('breed', 'service')},
            },
        ),
        migrations.CreateModel(
            name='BreedWeightThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_weight', models.DecimalField(decimal_places=2, help_text='Minimum weight in lbs (e.g., 50, 23.51, 99.19)', max_digits=6)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Extra charge for dogs weighing this amount or more', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_thresholds', to='mainapp.breed')),
            ],
            options={
                'ordering': ['breed__name', '-min_weight'],
                'unique_together': {('breed', 'min_weight')},
            },
        ),
    ]
