# Generated by Django 5.2.10 on 2026-01-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_breed_typical_weight_max_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicebreedprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicebreedprice',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='servicebreedprice',
            name='service',
        ),
        migrations.DeleteModel(
            name='BreedWeightThreshold',
        ),
        migrations.DeleteModel(
            name='ServiceBreedPrice',
        ),
    ]
