# Generated by Django 5.2.10 on 2026-01-30 03:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_servicebreedprice_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dog_age',
            field=models.CharField(blank=True, help_text="Dog's age for our records", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base starting price for this breed (for services requiring bath/grooming)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('base_required', 'Base Required (uses breed base price)'), ('standalone', 'Standalone (direct pricing)')], default='base_required', help_text='How this service is priced', max_length=20),
        ),
        migrations.AlterField(
            model_name='breedservicemapping',
            name='base_price',
            field=models.DecimalField(decimal_places=2, help_text='Custom service price (for standalone services only)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price for standalone services or add-on amount for base-required services', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this time slot')),
                ('start_time', models.TimeField(help_text='Start time (e.g., 09:00)')),
                ('end_time', models.TimeField(help_text='End time (e.g., 10:00)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slot is available for booking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='mainapp.groomer')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('groomer', 'date', 'start_time')},
            },
        ),
    ]
