# Generated by Django 5.2.10 on 2026-01-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_appointment_dog_age_breed_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='start_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting weight threshold in lbs (e.g., 15 lbs)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight_price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional charge per weight increment (e.g., $15 per 10 lbs)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='breed',
            name='weight_range_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight increment size in lbs (e.g., 10 lbs)', max_digits=6, null=True),
        ),
    ]
