# Generated by Django 5.2.10 on 2026-02-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_appointment_date_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
