# Generated by Django 5.2.10 on 2026-02-06 01:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_delete_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date', '-time'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name'], 'verbose_name': 'Breed', 'verbose_name_plural': 'Breeds'},
        ),
        migrations.AlterModelOptions(
            name='breedservicemapping',
            options={'ordering': ['breed__name', 'service__name'], 'verbose_name': 'Breed Service Mapping', 'verbose_name_plural': 'Breed Service Mappings'},
        ),
        migrations.AlterModelOptions(
            name='breedweightsurcharge',
            options={'ordering': ['breed__name', 'weight_range__order', 'weight_range__name'], 'verbose_name': 'Breed Weight Surcharge', 'verbose_name_plural': 'Breed Weight Surcharges'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='groomer',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Groomer', 'verbose_name_plural': 'Groomers'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Time Slot', 'verbose_name_plural': 'Time Slots'},
        ),
        migrations.AlterModelOptions(
            name='weightrange',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Weight Range', 'verbose_name_plural': 'Weight Ranges'},
        ),
        migrations.AlterModelOptions(
            name='weightrangetemplate',
            options={'ordering': ['name'], 'verbose_name': 'Weight Range Template', 'verbose_name_plural': 'Weight Range Templates'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(help_text='Customer for this appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='mainapp.customer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(db_index=True, help_text='Date of the appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dog_breed',
            field=models.ForeignKey(blank=True, help_text='Breed of the dog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mainapp.breed'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dog_name',
            field=models.CharField(help_text='Name of the dog', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dog_size',
            field=models.CharField(blank=True, help_text='Size of the dog', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='dog_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Dog's weight in lbs (measured at shop)", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='groomer',
            field=models.ForeignKey(blank=True, help_text='Groomer performing the service', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mainapp.groomer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the appointment', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='price_at_booking',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price at time of booking (for historical accuracy)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(help_text='Service being booked', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='mainapp.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Appointment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(db_index=True, help_text='Time of the appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='weight_range',
            field=models.ForeignKey(blank=True, help_text='Weight range for pricing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mainapp.weightrange'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(db_index=True, help_text='Name of the dog breed', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='start_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Starting weight threshold in lbs (e.g., 15 lbs)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='weight_price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional charge per weight increment (e.g., $15 per 10 lbs)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='breed',
            name='weight_range_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight increment size in lbs (e.g., 10 lbs)', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='breedweightsurcharge',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Breed-specific surcharge for this weight range', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, help_text="Customer's address", null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, help_text="Customer's email address", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, help_text="Customer's full name", max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text="Customer's phone number", max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +1234567890 or 1234567890. Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='groomer',
            name='bio',
            field=models.TextField(help_text='Professional biography'),
        ),
        migrations.AlterField(
            model_name='groomer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this groomer is currently active'),
        ),
        migrations.AlterField(
            model_name='groomer',
            name='name',
            field=models.CharField(help_text="Groomer's full name", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Service description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.IntegerField(help_text='Service duration in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(db_index=True, help_text='Service name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='groomer',
            field=models.ForeignKey(help_text='Groomer for this time slot', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='mainapp.groomer'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this slot is available for booking'),
        ),
        migrations.AlterField(
            model_name='weightrange',
            name='max_weight',
            field=models.DecimalField(decimal_places=2, help_text='Maximum weight in lbs', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='weightrange',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, help_text='Minimum weight in lbs', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='weightrange',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='weightrange',
            name='surcharge_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Extra charge for this weight range', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
