# Generated by Django 5.2.10 on 2026-02-06 03:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_appointment_options_alter_breed_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Dog's name", max_length=100)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text="Dog's weight in lbs", max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('age', models.CharField(blank=True, help_text="Dog's age (e.g., '2 years', '6 months')", max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the dog', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, help_text='Breed of the dog', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='mainapp.breed')),
                ('owner', models.ForeignKey(help_text='Customer who owns this dog', on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
                'ordering': ['name'],
            },
        ),
    ]
