# Generated by Django 5.2.10 on 2026-02-11 18:32

from django.db import migrations


def create_default_site_config(apps, schema_editor):
    """Create default site configuration with business hours and contact info."""
    SiteConfig = apps.get_model('mainapp', 'SiteConfig')

    # Only create if no active config exists
    if not SiteConfig.objects.filter(is_active=True).exists():
        SiteConfig.objects.create(
            business_name='Shampooches',
            address='123 Groom Street, Pet City, PC 12345',
            phone='5551234567',
            email='hello@shampooches.com',
            monday_open=8,
            monday_close=18,
            tuesday_open=8,
            tuesday_close=18,
            wednesday_open=8,
            wednesday_close=18,
            thursday_open=8,
            thursday_close=18,
            friday_open=8,
            friday_close=18,
            saturday_open=9,
            saturday_close=17,
            sunday_open=10,
            sunday_close=16,
            is_active=True,
        )


def reverse_create_default_site_config(apps, schema_editor):
    """Reverse migration - delete the default site configuration."""
    SiteConfig = apps.get_model('mainapp', 'SiteConfig')
    SiteConfig.objects.filter(
        business_name='Shampooches',
        address='123 Groom Street, Pet City, PC 12345'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_siteconfig'),
    ]

    operations = [
        migrations.RunPython(create_default_site_config, reverse_create_default_site_config),
    ]
