# Generated by Django 5.2.10 on 2026-02-11 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_create_default_site_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DogDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting deletion')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Status of the deletion request', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this request', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(help_text='Dog profile requested for deletion', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='mainapp.dog')),
                ('requested_by', models.ForeignKey(help_text='User who requested the deletion', on_delete=django.db.models.deletion.CASCADE, related_name='dog_deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dog Deletion Request',
                'verbose_name_plural': 'Dog Deletion Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
