# Generated by Django 5.2.10 on 2026-02-12 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_dogdeletionrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='breedweightsurcharge',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='breedweightsurcharge',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='breedweightsurcharge',
            name='weight_range',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='weight_range',
        ),
        migrations.DeleteModel(
            name='WeightRangeTemplate',
        ),
        migrations.DeleteModel(
            name='BreedWeightSurcharge',
        ),
        migrations.DeleteModel(
            name='WeightRange',
        ),
    ]
