# Generated by Django 5.2.10 on 2026-02-12 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preferred_groomer',
            field=models.ForeignKey(blank=True, help_text="Customer's preferred groomer (may differ from actual groomer if override slot was selected)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_appointments', to='mainapp.groomer'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='groomer',
            field=models.ForeignKey(blank=True, help_text='Groomer performing the service (this represents the actual groomer assigned to the appointment)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mainapp.groomer'),
        ),
    ]
