# Generated by Django 5.2.10 on 2026-02-14 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_customer_user_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the legal agreement', max_length=200)),
                ('content', models.TextField(help_text='Full text of the legal agreement')),
                ('effective_date', models.DateField(db_index=True, help_text='Date when this agreement version becomes effective')),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Whether this is the currently active agreement version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Legal Agreement',
                'verbose_name_plural': 'Legal Agreements',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='agreement_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the customer accepted the agreement', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='agreement_version',
            field=models.ForeignKey(blank=True, help_text='The legal agreement version the customer accepted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='mainapp.legalagreement'),
        ),
    ]
