# Generated by Django 5.2.10 on 2026-02-14 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_legalagreement_appointment_agreement_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Subject/topic of this conversation', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this thread is active (can receive new messages)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text='Customer user who initiated this thread', on_delete=django.db.models.deletion.CASCADE, related_name='customer_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Thread',
                'verbose_name_plural': 'Message Threads',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether this message has been read by recipients')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(help_text='Thread this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mainapp.messagethread')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen_at', models.DateTimeField(auto_now=True, help_text='Last time this user was confirmed to be viewing the thread')),
                ('thread', models.ForeignKey(help_text='Thread being viewed', on_delete=django.db.models.deletion.CASCADE, related_name='active_views', to='mainapp.messagethread')),
                ('user', models.ForeignKey(help_text='User viewing the thread', on_delete=django.db.models.deletion.CASCADE, related_name='thread_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thread View',
                'verbose_name_plural': 'Thread Views',
                'unique_together': {('thread', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TypingIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_typed_at', models.DateTimeField(auto_now=True, help_text='Last time this user was confirmed to be typing')),
                ('thread', models.ForeignKey(help_text='Thread where typing is happening', on_delete=django.db.models.deletion.CASCADE, related_name='typing_indicators', to='mainapp.messagethread')),
                ('user', models.ForeignKey(help_text='User who is typing', on_delete=django.db.models.deletion.CASCADE, related_name='typing_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Typing Indicator',
                'verbose_name_plural': 'Typing Indicators',
                'unique_together': {('thread', 'user')},
            },
        ),
    ]
