# Generated by Django 5.2.10 on 2026-02-14 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_messagethread_message_threadview_typingindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='max_dogs_per_day',
            field=models.IntegerField(default=3, help_text='Maximum number of dogs a customer can book in a single day', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
