# Generated by Django 5.2.10 on 2026-02-14 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0030_siteconfig_max_dogs_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text="Admin notes and customer classification tags (e.g., 'VIP', 'New Customer', 'Requires special handling')", null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_groomer',
            field=models.ForeignKey(blank=True, help_text="Customer's preferred groomer for bookings", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_customers', to='mainapp.groomer'),
        ),
    ]
